### ISSUE TITLE
Usar API Resource y paginación

### ISSUE THREAD

**Issue by cesargb** [crodg-dev/laravel-plesk-test#4]
Enfocate en este método para devolver un API Resource, además incorporá paginación, imagina devolver 1.000.000 productos. 

https://github.com/crodg-dev/laravel-plesk-test/blob/e434f4a23ce9b03bb6b2610a9171c93c24428edc/app/Http/Controllers/Api/ProductController.php#L14-L17

**Comment by crodg-dev** [comment]
Hecho.
